plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_8
    targetCompatibility = JavaVersion.VERSION_8
}

sourceSets {
    main {
        java.srcDirs = ['../api', 'src/main/java']
    }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
}

test {
    useJUnitPlatform()
}
